# /etc/dnsmasq.conf - FIXED
# Interface configuration - GUNAKAN enp2s0
interface=lo
interface=enp2s0
listen-address=127.0.0.1
listen-address=192.168.1.253

# Hotspot interface (ke client Wi-Fi)
interface=wlan0
listen-address=10.5.50.1

# Logging
log-queries
log-dhcp
log-facility=/var/log/dnsmasq.log

# Upstream DNS
#port 53
server=8.8.8.8
server=1.1.1.1
server=10.5.50.1
server=192.168.1.1
listen-address=127.0.0.1,192.168.1.253

# Important untuk capture semua query
no-resolv
no-hosts
bogus-priv
domain-needed
log-async=50
max-cache-ttl=0

# Tambahkan static DNS untuk login hotspot
address=/login.sunaryo.id/10.5.50.1
